---
# vars file for config-system
admin_packages:
  - wget
  - curl
  - git
  - net-tools
  - lsof
  - bash-completion
  - htop
  - iftop
  - ethtool
  - vim
  - lsb-release
  - apt-transport-https
  - ca-certificates
  - sudo
  - tree
  - zip

nc_packages:
  - php7.4
  - apache2
  - libapache2-mod-php7.4
  - php7.4-gd
  - php7.4-mysql
  - php7.4-curl
  - php7.4-mbstring
  - php7.4-intl

db_packages: mariadb-server

# pip_packages:

debian_version: buster

nextcloud_version: 21.0.3.1

nextcloud_versionstring: 21.0.3

domain: nc.ollemg.me

# configurações do banco de dados
db_username: nextcloud
db_password: nextcloud
db_name: nextcloud
db_hostname: ncdb01.ollemg.me
db_type: mysql
db_installed: false

data_dir: /var/www/nextcloud/data
work_dir: /var/www/nextcloud/

# MariaDB config
mariadb_config_bind: 0.0.0.0
mariadb_config_character: utf8mb4
mariadb_config_collation: utf8mb4_general_ci
mariadb_config_transaction_isolation: READ-COMMITTED
mariadb_config_binlog_format: ROW
mariadb_config_innodb_buffer_pool_size: 1GB
