---
# vars file for config-system
admin_packages:
  - wget
  - curl
  - git
  - net-tools
  - lsof
  - bash-completion
  - htop
  - iftop
  - ethtool
  - vim
  - lsb-release
  - apt-transport-https
  - ca-certificates
  - sudo
  - tree
  - zip
  - python-apt
  - debsecan
  - cifs-utils
  - redis-tools

php_version: 7.4

nc_packages:
  - apache2
  - libapache2-mod-php7.4
  - php{{ php_version }}
  - php{{ php_version }}-gd
  - php{{ php_version }}-mysql
  - php{{ php_version }}-curl
  - php{{ php_version }}-mbstring
  - php{{ php_version }}-intl
  - php{{ php_version }}-gmp
  - php{{ php_version }}-bcmath
  - php{{ php_version }}-imagick
  - php{{ php_version }}-xml
  - php{{ php_version }}-ldap
  - php{{ php_version }}-zip
  - php{{ php_version }}-apcu
  - php{{ php_version }}-redis
  - php{{ php_version }}-bz2
  - php{{ php_version }}-smbclient
  - php{{ php_version }}-ftp
  - php{{ php_version }}-fpm
  - libapache2-mod-fcgid
  - libmagickcore-dev
  - redis-server

db_packages: mariadb-server

debian_version: buster

nextcloud_versionstring: 21.0.3

nextcloud_version: "{{ nextcloud_versionstring}}.1"

domain: nc.ollemg.br

# Configurações do Nextcloud
nextcloud_admin_user: admin1
nextcloud_admin_pass: admin1
nextcloud_config_file: /var/www/nextcloud/config/config.php
nextcloud_config_dir: /var/www/nextcloud/config
data_dir: /mnt/nextcloud/data
work_dir: /var/www/nextcloud
ssl_dir: /etc/apache2/ssl
ssl_key: ollemg.br.key
ssl_crt: ollemg.br.crt
web_user: www-data
web_group: "{{ web_user }}"

# configurações do banco de dados
db_username: nextcloud
db_password: nextcloud
db_name: nextcloud
db_hostname: fox.ollemg.br
db_type: mysql
db_installed: false

# MariaDB config
mariadb_config_bind: 0.0.0.0
mariadb_config_character: utf8mb4
mariadb_config_collation: utf8mb4_general_ci
mariadb_config_transaction_isolation: READ-COMMITTED
mariadb_config_binlog_format: ROW
mariadb_config_innodb_buffer_pool_size: 1GB

# Redis Config

redis_port: 6379
redis_bind: 0.0.0.0

# Ansible Playbook config
role_web_dir: ./config_nc_web/files/

# apache config

apache_modules: 
  - ssl 
  - rewrite
  - headers