---
- name: Instala ferramentas administrativas
  apt:
    name: "{{ admin_packages }}"

- name: Importa a task de configuração do php
  import_tasks: php.yaml

- name: Importa a task de configuração do apache2
  import_tasks: apache.yaml

- name: Importa a task de configuração do php
  import_tasks: nextcloud.yaml
