---
- name: Instala ferramentas administrativas
  apt:
    name: "{{ admin_packages }}"

- name: Importa a task de configuração do Storage
  import_tasks: linux.yaml
  when: mount_enable == True

- name: Importa a task de configuração do PHP
  import_tasks: php.yaml

- name: Importa a task de configuração do apache2
  import_tasks: apache.yaml

- name: Importa a task de configuração do redis
  import_tasks: redis.yaml

- name: Importa a task de configuração do nextcloud
  import_tasks: nextcloud.yaml

