---
- name: Instala ferramentas administrativas
  apt:
    name: "{{ admin_packages }}"

- name: Adiciona a GPG Key do Repositorio PHP 7.4
  get_url:
    url: 'https://packages.sury.org/php/apt.gpg'
    dest: '/etc/apt/trusted.gpg.d/php.gpg'

- name: Adiciona repositorio do PHP 7.4
  apt_repository:
    repo: deb https://packages.sury.org/php/ "{{ debian_version }}" main
    state: present
    filename: php
    update_cache: true

- name: Instala PHP 7.4 e os modulos
  apt:
    name: "{{ nc_packages }}"

- name: Download nextcloud
  get_url:
    url: 'https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_versionstring }}.zip'
    dest: '/root/nextcloud-{{ nextcloud_versionstring }}.zip'

- name: Extrai nextcloud-{{ nextcloud_versionstring }}.zip Para /var/www/nextcloud
  unarchive:
    src: '/root/nextcloud-{{ nextcloud_versionstring }}.zip'
    dest: /var/www/
    remote_src: true

- name: Define as permissões do diretorio do nextcloud
  file:
    path: "{{ work_dir }}"
    owner: www-data
    group: www-data
    mode: '0655'

- name: Instala nextcloud
  shell: |
    php occ maintenance:install \
    --database={{ db_type }} \
    --databese-name={{ db_name }} \
    --database-host={{ db_hostname }} \
    --database-user={{ db_username }} \
    --database-pass={{ db_password }} \
    --data-dir={{ data_dir }}
  args:
    chdir: /var/www/nextcloud/
  become_user: www-data
  become: true

- name: define configuração do apache2
  template:
    src: apache.j2
    dest: '/etc/apache2/sites-available/{{ domain }}.conf'
    owner: root
    group: root
    mode: '0644'

- name: ativa o site
  command: /usr/sbin/a2ensite "{{ domain }}".conf
  args:
    chdir: /etc/apache2/sites-available/

- name: Inicia o Serviço do apache
  service:
    name: apache2
    state: started
    enabled: true
