---
- name: Instala ferramentas administrativas
  apt:
    name: "{{ admin_packages }}"

- name: Importa a task de configuração do php
  import_tasks: php.yml

- name: Importa a task de configuração do apache2
  import_tasks: apache2.yml

- name: Importa a task de configuração do php
  import_tasks: nextcloud.yml
