---
- name: Download e configuração do Nextcloud
  block:

    - name: Valida se o arquivo nextcloud-{{ nextcloud_versionstring }}.zip existe
      stat:
        path: '/root/nextcloud-{{ nextcloud_versionstring }}.zip'
      register: nexcloud_zip

    - name: Download nextcloud
      get_url:
        url: 'https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_versionstring }}.zip'
        dest: '/root/nextcloud-{{ nextcloud_versionstring }}.zip'
      when: not nexcloud_zip.stat.exists

    - name: Extrai nextcloud-{{ nextcloud_versionstring }}.zip Para {{ work_dir }}
      unarchive:
        src: '/root/nextcloud-{{ nextcloud_versionstring }}.zip'
        dest: /var/www/
        remote_src: true
      when: not nexcloud_zip.stat.exists

    - name: Define as permissões do diretorio do nextcloud
      file:
        path: "{{ work_dir }}"
        owner: "{{ web_user }}"
        group: "{{ web_user }}"
        mode: '0770'
        recurse: true

    - name: Define as permissões do diretorio de arquivos
      file:
        path: "{{ data_dir }}"
        owner: "{{ web_user }}"
        group: "{{ web_group }}"
        mode: '0770'
        recurse: true
      when: mount_enable == False

    - name: Valida se o arquivo config.php existe
      stat:
        path: "{{ nextcloud_config_file }}"
      register: nextcloud_install

    - name: Configurações personalizadas do nextcloud
      block:

        - name: Copia web.config.j2 para {{ nextcloud_config_dir}}
          template:
            src: web.config.php.j2
            dest: "{{ nextcloud_config_dir}}/web.config.php"
            owner: "{{ web_user }}"
            group: "{{ web_group }}"
            mode: '0770'
        
        - name: Copia log.config.j2 para {{ nextcloud_config_dir}}
          template:
            src: log.config.php.j2
            dest: "{{ nextcloud_config_dir}}/log.config.php"
            owner: "{{ web_user }}"
            group: "{{ web_group }}"
            mode: '0770'

        - name: Copia redis.config.j2 para {{ nextcloud_config_dir}}
          template:
            src: redis.config.php.j2
            dest: "{{ nextcloud_config_dir}}/redis.config.php"
            owner: "{{ web_user }}"
            group: "{{ web_group }}"
            mode: '0770'

        - name: Copia user.config.j2 para "{{ nextcloud_config_dir}}"
          template:
            src: user.config.php.j2
            dest: "{{ nextcloud_config_dir}}/user.config.php"
            owner: "{{ web_user }}"
            group: "{{ web_group }}"
            mode: '0770'

        - name: Copia proxy.config.j2 para "{{ nextcloud_config_dir}}"
          template:
            src: proxy.config.php.j2
            dest: "{{ nextcloud_config_dir}}/proxy.config.php"
            owner: "{{ web_user }}"
            group: "{{ web_group }}"
            mode: '0770'
          when: trusted_proxies is defined

    - name: Instala nextcloud
      shell: |
        sudo -u www-data php{{ php_version }} occ maintenance:install \
        --database {{ db_type }} \
        --database-name {{ db_name }} \
        --database-host {{ db_hostname }} \
        --database-user {{ db_username }} \
        --database-pass {{ db_password }} \
        --admin-user {{ nextcloud_admin_user }} \
        --admin-pass {{ nextcloud_admin_pass }} \
        --data-dir {{ data_dir }}
      args:
        chdir: "{{ work_dir }}"
      when: not nextcloud_install.stat.exists
      tags: install-nextcloud

    - name: Reinicia o Serviço do apache2
      service:
        name: apache2
        state: restarted
        enabled: true

    - name: Comando pra validar o status do Nextcloud
      command: sudo -u www-data php7.4 occ status
      args:
        chdir: "{{ work_dir }}"
      register: nextcloud_status
      when: work_dir is defined

    - name: Atualiza .htaccess
      command: sudo -u www-data php{{ php_version }} occ maintenance:update:htaccess
      args:
        chdir: "{{ work_dir }}"
      when: nextcloud_install.stat.exists

    - name: Status do Nextcloud
      debug:
        var: nextcloud_status.stdout_lines

  tags: nextcloud_block_config
