---
- name: Download e configuração do Nextcloud
  block:

    - name: Valida se o arquivo nextcloud-{{ nextcloud_versionstring }}.zip existe
      stat:
        path: '/root/nextcloud-{{ nextcloud_versionstring }}.zip'
      register: nexcloud_zip

    - name: Download nextcloud
      get_url:
        url: 'https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_versionstring }}.zip'
        dest: '/root/nextcloud-{{ nextcloud_versionstring }}.zip'
      when: not nexcloud_zip.stat.exists

    - name: Extrai nextcloud-{{ nextcloud_versionstring }}.zip Para /var/www/nextcloud
      unarchive:
        src: '/root/nextcloud-{{ nextcloud_versionstring }}.zip'
        dest: /var/www/
        remote_src: true
      when: not nexcloud_zip.stat.exists

    - name: Define as permissões do diretorio do nextcloud
      file:
        path: "{{ work_dir }}"
        owner: www-data
        group: www-data
        mode: '0770'
        recurse: true

    - name: Define as permissões do diretorio de arquivos
      file:
        path: "{{ data_dir }}"
        owner: www-data
        group: www-data
        mode: '0770'
        recurse: true

    - name: Valida se o arquivo config.php existe
      stat:
        path: "{{ nextcloud_config_file }}"
      register: nextcloud_install

    - name: copia nextcloud.j2 para /root/nextcloud.sh para subistituir os parametros trusted_domains e overwrite.cli.url
      template:
        src: nextcloud.j2
        dest: "/root/nextcloud.sh"
        owner: root
        group: root
        mode: '0777'


    - name: Instala nextcloud
      shell: |
        sudo -u www-data php7.4 occ maintenance:install \
        --database {{ db_type }} \
        --database-name {{ db_name }} \
        --database-host {{ db_hostname }} \
        --database-user {{ db_username }} \
        --database-pass {{ db_password }} \
        --admin-user {{ nextcloud_admin_user }} \
        --admin-pass {{ nextcloud_admin_pass }} \
        --data-dir {{ data_dir }}
      args:
        chdir: "{{ work_dir }}"
      when: not nextcloud_install.stat.exists
      tags: install-nextcloud

    - name: Executa script nextcloud.sh
      shell: /root/nextcloud.sh

    - name: Reinicia o Serviço do apache2
      service:
        name: apache2
        state: started
        enabled: true

    - name: Comando pra validar o status do Nextcloud
      command: sudo -u www-data php7.4 occ status
      args:
        chdir: "{{ work_dir }}"
      register: nextcloud_status
      when: work_dir is defined

    - name: Status do Nextcloud
      debug:
        var: nextcloud_status.stdout_lines

  tags: nextcloud_block_config
