---
- name: Download e configuração do Nextcloud
  block:

    - name: Valida se o arquivo nextcloud-{{ nextcloud_versionstring }}.zip existe
      stat:
        path: '/root/nextcloud-{{ nextcloud_versionstring }}.zip'
      register: nexcloud_zip

    - name: Download nextcloud
      get_url:
        url: 'https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_versionstring }}.zip'
        dest: '/root/nextcloud-{{ nextcloud_versionstring }}.zip'
      when: not nexcloud_zip.stat.exists

    - name: Extrai nextcloud-{{ nextcloud_versionstring }}.zip Para /var/www/nextcloud
      unarchive:
        src: '/root/nextcloud-{{ nextcloud_versionstring }}.zip'
        dest: /var/www/
        remote_src: true
      when: not nexcloud_zip.stat.exists

    - name: Define as permissões do diretorio do nextcloud
      file:
        path: "{{ work_dir }}"
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: true

    - name: Valida se o arquivo config.php existe
      stat:
        path: "{{ nextcloud_config_file }}"
      register: nextcloud_install

    - name: Instala nextcloud
      shell: |
        sudo -u www-data php7.4 occ maintenance:install \
        --database {{ db_type }} \
        --database-name {{ db_name }} \
        --database-host {{ db_hostname }} \
        --database-user {{ db_username }} \
        --database-pass {{ db_password }} \
        --admin-user {{ nextcloud_admin_user }} \
        --admin-pass {{ nextcloud_admin_pass }} \
        --data-dir {{ data_dir }}
      args:
        chdir: "{{ work_dir }}"
      become_user: root
      when: not nextcloud_install.stat.exists
      tags: install-nextcloud

    - name: Adiciona o dominio {{ domain }} na configuração do {{ nextcloud_config_file }}
      lineinfile:
        path: "{{ nextcloud_config_file }}"
        regexp: "localhost"
        line: "  'overwrite.cli.url' => 'http://{{ domain }}',"
      tags: config-nextcloud-domain

    - name: Edita o arquivo de configuração do nextcloud
      lineinfile:
        path: "{{ nextcloud_config_file }}"
        regexp: "localhost"
        line: "    0 => '{{ domain }}',"
      tags: config-nextcloud-domain2

    - name: Reinicia o Serviço do apache2
      service:
        name: apache2
        state: started
        enabled: true

    - name: Comando pra validar o status do Nextcloud
      command: sudo -u www-data php7.4 occ status
      args:
        chdir: "{{ work_dir }}"
      register: nextcloud_status
      when: work_dir is defined

    - name: Status do Nextcloud
      debug:
        var: nextcloud_status.stdout_lines
