---
- name: Instalação e configuração do PHP 7.4
  block:

    - name: Adiciona a GPG Key do Repositorio PHP 7.4
      get_url:
        url: 'https://packages.sury.org/php/apt.gpg'
        dest: '/etc/apt/trusted.gpg.d/php.gpg'

    - name: Adiciona repositorio do PHP 7.4
      apt_repository:
        repo: deb https://packages.sury.org/php/ {{ debian_version }} main
        state: present
        filename: php
        update_cache: true
      tags: repo

    - name: Instala PHP 7.4 e os modulos
      apt:
        name: "{{ nc_packages }}"
