---
- name: Instalação e configuração do php{{ php_version }}
  block:

    - name: Adiciona a GPG Key do Repositorio PHP {{ php_version }}
      get_url:
        url: 'https://packages.sury.org/php/apt.gpg'
        dest: '/etc/apt/trusted.gpg.d/php.gpg'

    - name: Adiciona repositorio do php{{ php_version }}
      apt_repository:
        repo: deb https://packages.sury.org/php/ {{ debian_version }} main
        state: present
        filename: php
        update_cache: true
      tags: repo

    - name: Instala {{ nc_packages }}
      apt:
        name: "{{ nc_packages }}"
